# Generated by Django 4.2.4 on 2023-08-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='properties',
            new_name='property',
        ),
    ]
